### ISSUE TITLE
Button does not work well if used multiple times on page.

### ISSUE THREAD

**Issue by thubalek** [igrigorik/hackernews-button#10]
I used your button at http://www.batterywidgetreborn.com/known-bugs.html and it renders well just only at fraction of places where it is put. 

Works well if used just a few times.

**Comment by igrigorik** [comment]
Hmm, interesting - thanks for reporting this. Don't see the buttons at all on the site. Guessing, you removed them? Do you have any other demo pages where the problem is still present?

**Comment by thubalek** [comment]
Thanks for getting back to me. I just turned it back to help your investigation.

Here is also screenshot:
http://cl.ly/image/3N0T252E320h

**Comment by igrigorik** [comment]
@thubalek looking at your page source.. you want to place the javascript snippet to load the JS at the bottom of the page. Much better performance.. and it may solve your problem with multiple buttons as well.

**Comment by thubalek** [comment]
@igrigorik It helped. Thanks a lot.

**Comment by igrigorik** [comment]
Awesome!
