### ISSUE TITLE
Please use protocol relative URLs

### ISSUE THREAD

**Issue by olegp** [igrigorik/hackernews-button#13]
So on this line:

https://github.com/igrigorik/hackernews-button/blob/master/static/hn.js#L26

Please use the following URL: `//hnbutton.appspot.com` instead of `http://hnbutton.appspot.com`

This will avoid mixed content warnings in browsers on sites that serve the button via HTTPS, such as https://starthq.com

Many thanks!

/cc @alexlamsl

**Comment by igrigorik** [comment]
Done, deployed - thanks for reporting this.
