### ISSUE TITLE
The hnsearch api appears to be down

### ISSUE THREAD

**Issue by joshblum** [igrigorik/hackernews-button#14]
```
  wget http://api.thriftdb.com/api.hnsearch.com/items/_search?
  --2014-08-26 23:13:51--  http://api.thriftdb.com/api.hnsearch.com/items/_search?
  Resolving api.thriftdb.com... 54.236.170.141, 107.23.43.191
  Connecting to api.thriftdb.com|54.236.170.141|:80... connected.
  HTTP request sent, awaiting response... No data received.
  Retrying.
```

**Comment by igrigorik** [comment]
Hmm, indeed... api.thriftdb.com appears to be down, and has been for the past few days. Yikes. Any idea what happened there? Doing a bit of digging, it looks like hn.algolia.com/api could serve as a replacement. Example query:

http://hn.algolia.com/api/v1/search_by_date?query=http://www.theguardian.com/technology/2014/aug/26/amazon-fire-phone-sales-data

Seems to return what we need!

**Comment by joshblum** [comment]
Awesome! Do you want to update or should I submit pull request?

**Comment by igrigorik** [comment]
Whoever gets to it first.. Me, probably not before the weekend. :)

**Comment by igrigorik** [comment]
Resolved and deployed! Kudos to @redox for awesome API :)

**Comment by redox** [comment]
:+1:
