### ISSUE TITLE
Big version with balloon on top?

### ISSUE THREAD

**Issue by f055** [igrigorik/hackernews-button#2]
It would be nice to have a visual compatibility with twitter widget etc.

**Comment by igrigorik** [comment]
Hmm, agreed! Need to reverse engineer one of the Twitter or similar buttons for a bulletproof style to make it happen. Unless you have something handy?

**Comment by panzi** [comment]
A 55x62 pixel version would be nice (for some reason this odd resolution became the standard for the big buttons with the balloon on top). I think once this is supported I'll add it to my social share privacy fork: http://panzi.github.com/SocialSharePrivacy/
