### ISSUE TITLE
Make the button "standard" height to match Twitter and G+ buttons

### ISSUE THREAD

**Issue by mixinmax** [igrigorik/hackernews-button#7]
I've currently got a Twitter button and a Google Plus button and decided to add the HN button as well. However, the HN button doesn't line up vertically with the other buttons. I've attributed this to the HN icon only being 19px high, while the others are 20px.

This really is just a cosmetic issue and isn't critical, but I would prefer have a homogeneous sharing zone on my website. Having the HN button just 1 pixel off is noticeable.

Here's a screenshot from my site:

![preview](http://oi50.tinypic.com/2md02ew.jpg)

**Comment by igrigorik** [comment]
Hmm, are you sure about the 19px? Inspecting the button on my own site shows 20px height on the injected iframe?

http://img.skitch.com/20120426-m5iuamukjsicsbfr3h1gc7dtqe.png

**Comment by mixinmax** [comment]
Sorry, I might have been ambiguous in my explanation. I'm saying the twitter button is 20px, but the HN icon seems to be a pixel smaller. You can see it in your screenshot too, the bottom of the HN icon doesn't line up with the bottom of the Twitter icon.

**Comment by igrigorik** [comment]
Ahh, I see.. Right, this is actually of my own making. For some reason when I added the extra pixel the iframe would break in FF and would add scrollbars. My "quick and dirty" hack at the time was to reduce the line-height by a pixel.

Need to figure out why FF is adding that extra pixel.. and we can fix the missing pixel issue. If you have any ideas or suggestions, that'd be very helpful. :)

"line-height:13px" should be 14px on hb_bt

https://github.com/igrigorik/hackernews-button/commit/560b3a528940450c6719cd5cffa90688ca4d617a

**Comment by mixinmax** [comment]
Hmm...weird. Did the scrollbar only show up in FF? Would it be possible to make the iframe 21px and the icon 20px? I'm afraid I won't be able to help much seeing as I've never done any javascript :)

**Comment by igrigorik** [comment]
21px would actually make the problem even worse. Instead of coming up pixel short it would actually push the entire line one pixel down, which has a higher likelihood of breaking people's layouts. 

Having said that, think I have an idea for a simple fix.. Will give it a try on the weekend.

**Comment by mixinmax** [comment]
Awesome, thanks for the explanation. Hopefully your idea works.

**Comment by igrigorik** [comment]
Bumped the line height by 1px: https://github.com/igrigorik/hackernews-button/commit/0a25b085a099bfb1540bc6dd68cdd511973406b0
